version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MARIADB_ROOT_PASSWORD=root
      - MYSQL_DATABASE=openxeco
      - MYSQL_USER=openxeco
      - MYSQL_PASSWORD=openxeco-pwd
    ports:
      - '3366:3306'
    expose:
      - '3366'
    volumes:
      - ./.docker/mariadb/data:/var/lib/mariadb/data
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 5s
      retries: 10

  smtp:
    # MacBook Pro chip M1: smtp The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
    platform: linux/x86_64
    image: reachfive/fake-smtp-server
    environment:
      - MAIL_SERVER=smtp
      - MAIL_PORT=1025
      - MAIL_USE_TLS=True
      - MAIL_USE_SSL=False
      - MAIL_DEFAULT_SENDER=my-default-sender@example.org
    ports:
      - "1025:1025"
      - "1080:1080"

  oxe-web-admin:
    build:
      context: .
      dockerfile: oxe-web-admin/.docker/Dockerfile
    tty: true
    volumes:
      - ./oxe-web-admin:/usr/app
      - /usr/app/node_modules
    command: npm start
    ports:
      - "3000:3000"
    expose:
      - '3000'
    depends_on:
      mariadb:
        condition: service_healthy

  oxe-web-community:
    build:
      context: .
      dockerfile: oxe-web-community/.docker/Dockerfile
    tty: true
    volumes:
      - ./oxe-web-community:/usr/app
      - /usr/app/node_modules
    command: npm start
    ports:
      - "3001:3001"
    expose:
      - '3001'
    depends_on:
      mariadb:
        condition: service_healthy

  oxe-api:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    restart: always
    volumes:
      - ./.docker/media:/usr/app/media
      - ./.docker/documents:/usr/app/documents
      - ./oxe-api:/usr/app
    ports:
      - "5000:5000"
    expose:
      - '5000'
    environment:
      - DEBUG=true
      - DB_HOSTNAME=mariadb
      - DB_NAME=openxeco
      - DB_USERNAME=openxeco
      - DB_PASSWORD=openxeco-pwd
      - DB_PORT=3306
      - DB_DRIVER=mysql+pymysql
      - JWT_SECRET_KEY=some_random_secret
      - MAIL_SERVER=foo_mail_server
      - MAIL_PORT=foo_mail_port
      - MAIL_USERNAME=foo_mail_username
      - MAIL_PASSWORD=foo_mail_password
      - MAIL_USE_TLS=True
      - MAIL_USE_SSL=True
      - IMAGE_FOLDER=/usr/app/media
      - DOCUMENT_FOLDER=/usr/app/documents
      - MAIL_DEFAULT_SENDER=openxeco@localhost.localdomain
      - INITIAL_ADMIN_EMAIL=your.email@localhost.localdomain
    depends_on:
      mariadb:
        condition: service_healthy

networks:
  default:
    name: openxeco
    external: true
